name: bill_splitter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: any
  http: any
  fluttertoast: 7.0.1
  firebase_core: ^1.12.0
  firebase_database: 9.0.5
  firebase_database_platform_interface: 0.2.0+5
  shared_preferences: 2.0.7
  lottie: 1.2.0
  progress_dialog: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/montserrat_bold.otf
        - asset: assets/fonts/montserrat_extra_bold.otf
        - asset: assets/fonts/montserrat_light.otf
        - asset: assets/fonts/montserrat_medium.otf
        - asset: assets/fonts/montserrat_regular.otf
        - asset: assets/fonts/montserrat_semi_bold.otf
        - asset: assets/fonts/montserrat_thin.otf